settings:
  # Время действия обычной адаптации в секундах
  duration-normal: 10
  
  # Время действия повышенной адаптации в секундах
  duration-super: 4

  # Бонус времени в секундах за каждый профильный удар
  hit-bonus-normal: 0.2
  hit-bonus-super: 0.8

  # Сколько нужно получить ударов для обычной адаптации в зависимости от уровня
  required-hits:
    lvl1: 10
    lvl2: 8
    lvl3: 6

  # Сколько ударов нужно получить во время обычной адаптации для перехода в супер-режим
  required-super-hits: 8
