name: f8-daptation-sosicka-bobr551
version: 8
main: com.yourserver.adaptation.AdaptationPlugin
api-version: 1.20

commands:
  adaptation:
    description: управление плагином f9-daptation-sosika-bobr551
    permission: adaptation.admin
    usage: /adaptation <give/reload>
